<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSu7nzq9\src_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSu7nzq9/src_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSu7nzq9.legacy');

    return;
}

if (!\class_exists(src_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSu7nzq9\src_KernelDevDebugContainer::class, src_KernelDevDebugContainer::class, false);
}

return new \ContainerSu7nzq9\src_KernelDevDebugContainer([
    'container.build_hash' => 'Su7nzq9',
    'container.build_id' => '40069949',
    'container.build_time' => 1657535120,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSu7nzq9');
